name: Synchronize Back to master

on:
  push:
    branches:
      - openldap26

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - uses: actions/checkout@v2
        with:
          ref: openldap26
      - run: |
          git fetch --unshallow
          git pull origin openldap26
          git config user.email "automatic@github.com"
          git config user.name "GitHub Actions"
      - name: sync master
        run: |
          git checkout master
          git pull --rebase
          git merge openldap26 --ff-only
          git push
